Added tests, psalm and phpcs fixes
dotkernel/dot-flashmessenger pull request #12
Opened 2023-08-17 16:22 UTC by Jurj-Bogdan

#10

2023-08-17 16:23 UTC, Jurj-Bogdan commented
@arhimede a symfony insight badge would be needed

2023-08-17 17:58 UTC, alexmerlin requested changes
Please restore file permissions (`755` -> `644`) for the following files:
* `.gitignore`
* `CHANGELOG.md`
* `LICENSE.md`
* `OSSMETADATA`
* `README.md`
* `composer.json`

2023-08-17 17:58 UTC, alexmerlin commented on README.md
> +[![GitHub license](https://img.shields.io/github/license/dotkernel/dot-flashmessenger)](https://github.com/dotkernel/dot-flashmessenger/blob/3.4.0/LICENSE.md)
```suggestion
[![GitHub license](https://img.shields.io/github/license/dotkernel/dot-flashmessenger)](https://github.com/dotkernel/dot-flashmessenger/blob/3.0/LICENSE.md)
```

2023-08-17 17:58 UTC, alexmerlin commented on composer.json
> +        "mikey179/vfsstream": "^v1.6.11",
```suggestion
```

2023-08-17 17:58 UTC, alexmerlin commented on test/FlashMessengerTest.php
> +        $container->setAccessible(true);
```suggestion
```

2023-08-17 17:58 UTC, alexmerlin commented on test/FlashMessengerTest.php
> +        $container->setAccessible(true);
```suggestion
```

2023-08-18 06:07 UTC, alexmerlin requested changes
I just noticed that the permissions have changed on the files in the `src` directory too.
Please restore those as well (`755` -> `644`).

2023-08-18 09:21 UTC, alexmerlin approved these changes

2023-08-18 09:21 UTC, merged